---
name: Build API/client files

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - ".github/workflows/**"
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/workflows/**"

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Create TXT for testing
        run: echo "This is a test" > test.txt

      - name: Upload build as artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        if: always()
        with:
          name: test.txt
          path: ./test.txt
